# Generated by Django 4.2.7 on 2023-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_borrowingbook_borrowed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="received_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
