# Generated by Django 4.2.7 on 2023-11-12 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_book_received_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="received_in",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
