# Generated by Django 4.2.7 on 2023-11-12 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_book_received_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowingbook",
            name="borrowed_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="borrowingbook",
            name="returned_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
