# Generated by Django 4.2.7 on 2023-11-12 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_borrowingbook_borrowed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="received_in",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="borrowingbook",
            name="borrowed_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="borrowingbook",
            name="returned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
